export const info = [
    {
        name: 'Jason Chaliff',
        title: 'Associate',
        number: '404.500.8961',
        email: 'info@Jason Chaliffcom',
        text: 'Michael Davis brings nearly 20 years of real estate development and construction experience toKapco Properties LL Group. Prior to launching Kapco Properties LLC, Michael served as SeniorDevelopment Manager with North AmericanProperties taking the development lead on theAvalon project, a 1 billion dollar mixed-use Projeclocated in Alpharetta, GA. While steering the Projectthrough thedevelopment processhis responsibilitie sMichael Davis brings nearly 20yearsofreal estate development and construction experience to Kapco Properties LL Group. Prior to launching Kapco Properties LLC, Michael served as Senior Development Manager with North American Properties taking the development lead on the Avalon project, a 1 billion dollar mixed-use Project located in Alpharetta, GA. While steering the Project through the development process his responsibilities Michael Davis brings nearly 20 years of real estatedevelopment and construction experience toKapco Properties LL Group. Prior to launching Kapco Properties LLC, Michael served as SeniorDevelopment Manager with North AmericanProperties taking the development lead on theAvalon project, a 1 billion dollar mixed-use Projeclocated in Alpharetta, GA. While steering the Projectthrough thedevelopment processhis responsibilitie sMichael Davis brings nearly 20yearsofreal estate development and construction experience to Kapco Properties LL Group. Prior to launching Kapco Properties LLC, Michael served as Senior Development Manager with North American Properties taking the development lead on the Avalon project, a 1 billion dollar mixed-use Project located in Alpharetta, GA. While steering the Project through the development process his responsibilities',
        backgroundColor: '#F1B170'
    },
    {
        name: 'Rebecca',
        title: 'Associate',
        number: '404.500.8961',
        email: 'info@Rebecca Freedman',
        text: 'Michael Davis brings nearly 20 years of real estate development and construction experience toKapco Properties LL Group. Prior to launching Kapco Properties LLC, Michael served as SeniorDevelopment Manager with North AmericanProperties taking the development lead on theAvalon project, a 1 billion dollar mixed-use Projeclocated in Alpharetta, GA. While steering the Projectthrough thedevelopment processhis responsibilitie sMichael Davis brings nearly 20yearsofreal estate development and construction experience to Kapco Properties LL Group. Prior to launching Kapco Properties LLC, Michael served as Senior Development Manager with North American Properties taking the development lead on the Avalon project, a 1 billion dollar mixed-use Project located in Alpharetta, GA. While steering the Project through the development process his responsibilities Michael Davis brings nearly 20 years of real estatedevelopment and construction experience toKapco Properties LL Group. Prior to launching Kapco Properties LLC, Michael served as SeniorDevelopment Manager with North AmericanProperties taking the development lead on theAvalon project, a 1 billion dollar mixed-use Projeclocated in Alpharetta, GA. While steering the Projectthrough thedevelopment processhis responsibilitie sMichael Davis brings nearly 20yearsofreal estate development and construction experience to Kapco Properties LL Group. Prior to launching Kapco Properties LLC, Michael served as Senior Development Manager with North American Properties taking the development lead on the Avalon project, a 1 billion dollar mixed-use Project located in Alpharetta, GA. While steering the Project through the development process his responsibilities',
        backgroundColor: '#F1B170'
    },
    {
        name: 'Jane Mark',
        title: 'Associate',
        number: '404.500.8961',
        email: 'info@Jane Mark',
        text: 'Michael Davis brings nearly 20 years of real estate development and construction experience toKapco Properties LL Group. Prior to launching Kapco Properties LLC, Michael served as SeniorDevelopment Manager with North AmericanProperties taking the development lead on theAvalon project, a 1 billion dollar mixed-use Projeclocated in Alpharetta, GA. While steering the Projectthrough thedevelopment processhis responsibilitie sMichael Davis brings nearly 20yearsofreal estate development and construction experience to Kapco Properties LL Group. Prior to launching Kapco Properties LLC, Michael served as Senior Development Manager with North American Properties taking the development lead on the Avalon project, a 1 billion dollar mixed-use Project located in Alpharetta, GA. While steering the Project through the development process his responsibilities Michael Davis brings nearly 20 years of real estatedevelopment and construction experience toKapco Properties LL Group. Prior to launching Kapco Properties LLC, Michael served as SeniorDevelopment Manager with North AmericanProperties taking the development lead on theAvalon project, a 1 billion dollar mixed-use Projeclocated in Alpharetta, GA. While steering the Projectthrough thedevelopment processhis responsibilitie sMichael Davis brings nearly 20yearsofreal estate development and construction experience to Kapco Properties LL Group. Prior to launching Kapco Properties LLC, Michael served as Senior Development Manager with North American Properties taking the development lead on the Avalon project, a 1 billion dollar mixed-use Project located in Alpharetta, GA. While steering the Project through the development process his responsibilities',
        backgroundColor: '#F1B170'
    },
    {
        name: 'Jared Siegel',
        title: 'Associate',
        number: '404.500.8961',
        email: 'info@Jared Siegel',
        text: 'Michael Davis brings nearly 20 years of real estate development and construction experience toKapco Properties LL Group. Prior to launching Kapco Properties LLC, Michael served as SeniorDevelopment Manager with North AmericanProperties taking the development lead on theAvalon project, a 1 billion dollar mixed-use Projeclocated in Alpharetta, GA. While steering the Projectthrough thedevelopment processhis responsibilitie sMichael Davis brings nearly 20yearsofreal estate development and construction experience to Kapco Properties LL Group. Prior to launching Kapco Properties LLC, Michael served as Senior Development Manager with North American Properties taking the development lead on the Avalon project, a 1 billion dollar mixed-use Project located in Alpharetta, GA. While steering the Project through the development process his responsibilities Michael Davis brings nearly 20 years of real estatedevelopment and construction experience toKapco Properties LL Group. Prior to launching Kapco Properties LLC, Michael served as SeniorDevelopment Manager with North AmericanProperties taking the development lead on theAvalon project, a 1 billion dollar mixed-use Projeclocated in Alpharetta, GA. While steering the Projectthrough thedevelopment processhis responsibilitie sMichael Davis brings nearly 20yearsofreal estate development and construction experience to Kapco Properties LL Group. Prior to launching Kapco Properties LLC, Michael served as Senior Development Manager with North American Properties taking the development lead on the Avalon project, a 1 billion dollar mixed-use Project located in Alpharetta, GA. While steering the Project through the development process his responsibilities',
        backgroundColor: '#F1B170'
    }
]